### ISSUE TITLE
issues with SHA1 Results

### ISSUE THREAD

**Issue by superautomationman** [marvin-mangold/S7-PLC_SHA1#1]
I have implemented this code in an S71200 PLC but I cannot get the SHA1 to give the results expected.

This is what is calculated online.
![Capture](https://user-images.githubusercontent.com/92455930/137175554-31e20e9a-691a-4f1d-98a4-c1108e482244.PNG)

This does not match the results from the block
![online](https://user-images.githubusercontent.com/92455930/137176690-181d95b4-53d8-4136-9e6c-2dfc6c76c696.PNG)

**Comment by superautomationman** [comment]
Please help I cannot duplicate the results you have gotten.

I have attached my project as a reference.
[calculate_SHA1.zip](https://github.com/marvin-mangold/S7-PLC_SHA1/files/7340008/calculate_SHA1.zip)

**Comment by marvin-mangold** [comment]
I will have a look.
I do not have TIA V17, i can only test with V15.1.

**Comment by marvin-mangold** [comment]
I have tested it in a fresh project, simulating a PLC S7-1200 AC/DC/RLY with Firmware V4.3 with TIA Portal V15.1.
At the moment i am not shure if this is a problem with TIA V17 or with the newer firmware of the PLC. 
Maybe you can try to open the V15.1 Project (attached) with your TIA V17 so the project will be migrated to TIA V17 and then test it with simulation or real PLC? 

![test](https://user-images.githubusercontent.com/10088323/137180184-694e42a8-1383-4295-b216-1cbd4d0db58b.JPG)

Here is the project i have tested 10 minutes ago:
[TestProject.zip](https://github.com/marvin-mangold/S7-PLC_SHA1/files/7340141/TestProject.zip)

Are you shure the FC is unchanged? Maybe you unintentionally changed something in the code?

And you should try another Website for your sha1 test.
Because i had issues with this websites sha1 calculator some time ago.

**Comment by superautomationman** [comment]
I re-imported the scl and recompiled all and now it is working.

Thanks for the code and the response.

**Comment by marvin-mangold** [comment]
nice, have fun with the Function :)
